spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/batchsevendata2
    username: postgres
    password: utkarshutc212629

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  servlet:
    context-path: /api
  port: 8881

springdoc:
  show-actuator: true
  packages-to-scan: "com.tw.prograd"

storage:
  initialize: true
  location: images